//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _0507_Client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IBook")]
    public interface IBook {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBook/AddBook", ReplyAction="http://tempuri.org/IBook/AddBookResponse")]
        void AddBook(string title, string author, int price, byte[] image);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBook/AddBook", ReplyAction="http://tempuri.org/IBook/AddBookResponse")]
        System.Threading.Tasks.Task AddBookAsync(string title, string author, int price, byte[] image);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBook/UpdateBook", ReplyAction="http://tempuri.org/IBook/UpdateBookResponse")]
        void UpdateBook(string title, string author, int price, byte[] image);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBook/UpdateBook", ReplyAction="http://tempuri.org/IBook/UpdateBookResponse")]
        System.Threading.Tasks.Task UpdateBookAsync(string title, string author, int price, byte[] image);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBook/DeleteBook", ReplyAction="http://tempuri.org/IBook/DeleteBookResponse")]
        bool DeleteBook(string title, string author);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBook/DeleteBook", ReplyAction="http://tempuri.org/IBook/DeleteBookResponse")]
        System.Threading.Tasks.Task<bool> DeleteBookAsync(string title, string author);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBook/GetBook1", ReplyAction="http://tempuri.org/IBook/GetBook1Response")]
        _0507_Client.ServiceReference1.GetBook1Response GetBook1(_0507_Client.ServiceReference1.GetBook1Request request);
        
        // CODEGEN: 작업에 여러 개의 반환 값이 있기 때문에 메시지 계약을 생성하는 중입니다.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBook/GetBook1", ReplyAction="http://tempuri.org/IBook/GetBook1Response")]
        System.Threading.Tasks.Task<_0507_Client.ServiceReference1.GetBook1Response> GetBook1Async(_0507_Client.ServiceReference1.GetBook1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBook/GetBookList", ReplyAction="http://tempuri.org/IBook/GetBookListResponse")]
        System.Collections.Generic.Dictionary<string, string> GetBookList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBook/GetBookList", ReplyAction="http://tempuri.org/IBook/GetBookListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> GetBookListAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBook1", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetBook1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string title;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string author;
        
        public GetBook1Request() {
        }
        
        public GetBook1Request(string title, string author) {
            this.title = title;
            this.author = author;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBook1Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetBook1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int price;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public byte[] image;
        
        public GetBook1Response() {
        }
        
        public GetBook1Response(int price, byte[] image) {
            this.price = price;
            this.image = image;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBookChannel : _0507_Client.ServiceReference1.IBook, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookClient : System.ServiceModel.ClientBase<_0507_Client.ServiceReference1.IBook>, _0507_Client.ServiceReference1.IBook {
        
        public BookClient() {
        }
        
        public BookClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddBook(string title, string author, int price, byte[] image) {
            base.Channel.AddBook(title, author, price, image);
        }
        
        public System.Threading.Tasks.Task AddBookAsync(string title, string author, int price, byte[] image) {
            return base.Channel.AddBookAsync(title, author, price, image);
        }
        
        public void UpdateBook(string title, string author, int price, byte[] image) {
            base.Channel.UpdateBook(title, author, price, image);
        }
        
        public System.Threading.Tasks.Task UpdateBookAsync(string title, string author, int price, byte[] image) {
            return base.Channel.UpdateBookAsync(title, author, price, image);
        }
        
        public bool DeleteBook(string title, string author) {
            return base.Channel.DeleteBook(title, author);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteBookAsync(string title, string author) {
            return base.Channel.DeleteBookAsync(title, author);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _0507_Client.ServiceReference1.GetBook1Response _0507_Client.ServiceReference1.IBook.GetBook1(_0507_Client.ServiceReference1.GetBook1Request request) {
            return base.Channel.GetBook1(request);
        }
        
        public int GetBook1(string title, string author, out byte[] image) {
            _0507_Client.ServiceReference1.GetBook1Request inValue = new _0507_Client.ServiceReference1.GetBook1Request();
            inValue.title = title;
            inValue.author = author;
            _0507_Client.ServiceReference1.GetBook1Response retVal = ((_0507_Client.ServiceReference1.IBook)(this)).GetBook1(inValue);
            image = retVal.image;
            return retVal.price;
        }
        
        public System.Threading.Tasks.Task<_0507_Client.ServiceReference1.GetBook1Response> GetBook1Async(_0507_Client.ServiceReference1.GetBook1Request request) {
            return base.Channel.GetBook1Async(request);
        }
        
        public System.Collections.Generic.Dictionary<string, string> GetBookList() {
            return base.Channel.GetBookList();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> GetBookListAsync() {
            return base.Channel.GetBookListAsync();
        }
    }
}
