//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _0508_WCF_ClientExample.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ICal", CallbackContract=typeof(_0508_WCF_ClientExample.ServiceReference1.ICalCallback))]
    public interface ICal {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICal/Add")]
        void Add(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICal/Add")]
        System.Threading.Tasks.Task AddAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICal/Sub")]
        void Sub(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICal/Sub")]
        System.Threading.Tasks.Task SubAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICal/Mul")]
        void Mul(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICal/Mul")]
        System.Threading.Tasks.Task MulAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICal/Div")]
        void Div(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICal/Div")]
        System.Threading.Tasks.Task DivAsync(int a, int b);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICal/Result")]
        void Result([System.ServiceModel.MessageParameterAttribute(Name="result")] float result1);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalChannel : _0508_WCF_ClientExample.ServiceReference1.ICal, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalClient : System.ServiceModel.DuplexClientBase<_0508_WCF_ClientExample.ServiceReference1.ICal>, _0508_WCF_ClientExample.ServiceReference1.ICal {
        
        public CalClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public CalClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public CalClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public CalClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public CalClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Add(int a, int b) {
            base.Channel.Add(a, b);
        }
        
        public System.Threading.Tasks.Task AddAsync(int a, int b) {
            return base.Channel.AddAsync(a, b);
        }
        
        public void Sub(int a, int b) {
            base.Channel.Sub(a, b);
        }
        
        public System.Threading.Tasks.Task SubAsync(int a, int b) {
            return base.Channel.SubAsync(a, b);
        }
        
        public void Mul(int a, int b) {
            base.Channel.Mul(a, b);
        }
        
        public System.Threading.Tasks.Task MulAsync(int a, int b) {
            return base.Channel.MulAsync(a, b);
        }
        
        public void Div(int a, int b) {
            base.Channel.Div(a, b);
        }
        
        public System.Threading.Tasks.Task DivAsync(int a, int b) {
            return base.Channel.DivAsync(a, b);
        }
    }
}
